[patch.crates-io]
burn = { git = "https://github.com/tracel-ai/burn", rev = "cc8f6d44d39b6192cd233c92f6e49134d81ab05f" }
burn-central = { git = "https://github.com/tracel-ai/burn-central", branch = "artifact-error-message" }
